#!/bin/bash
DIR="$(dirname "$(dirname "$(realpath "$0")")")"
cd "$DIR/preload"

if [ "$1" == "reset" ];then
echo -ne >"$DIR/appdir"
shift
fi
cd ".$1"
function fastpreload {
printf "["	
if [ ! "$1" == / ] && [ ! "$1" == "" ];then
printf "{\"name\": \"back\",\"label\":\"Back\",\"status\":\"\",\"icon\":\"xxxxxxxxxxxxx\",\"color\":\"#008000\"},"
fi
while read line
do if [ -f "$line" ]
then cat "$line"
elif [ -d "$line" ]
then printf "{\"name\": \"$line\",\"label\":\"$line\",\"status\":\"\",\"icon\":\"$PWD/$line/icon.png\",\"color\":\"#0000ff\"}"
fi
printf ","
done 
printf "]"
}

ls -X | grep -v ".\.png" | fastpreload "$1"| sed -e 's/,]/]/g'>$DIR/tmp.json

