#!/bin/bash
#This file create and manage queue
DIR="$(dirname "$(realpath "$0")")"
function managing {
	act="$1"
	printf "$1ing " && shift && echo $@
	app=$1
	shift
	until [ "$1" == "" ];do
		app="$app $1"
		shift
	done
	"$DIR/manage" "$act" "$app" && echo "$acted" >"$DIR/status/$app"
	if [ $? != 0 ];then
		echo "corrupted">"$DIR/status/$app"
	fi
}
while read line;do
	if echo "$line" | grep "install" >/dev/null;then
			managing $line
			#|| message fail "Failled to $action $app" && sed -i "s/$actioning/corrupted/g" /tmp/pi-apps_queue
	elif [ "$line" == "exit" ];then
			exit
	fi
done
